---
- name: Install BackUp Scripts for Logs and SQL - by JPIL Software
  hosts: all
  vars:
    git_passowrd: 
    git_user: jpilsoftware
  tasks:
    - name: Install git
      yum:
        name: git
        state: latest

    - name: Clone backup Script for MySQL
      shell: wget https://raw.githubusercontent.com/jpilsoftware-uy/sistemas-operativos/main/Scripts/backup_sql.sh

    - name: Clone logs backup for Logs
      shell: wget https://raw.githubusercontent.com/jpilsoftware-uy/sistemas-operativos/main/Scripts/backup_logs.sh