---
- name: Install BackUp Scripts for Logs and SQL - by JPIL Software
  hosts: all
  tasks:

    - name: Create a folder to place scripts
      shell: mkdir -p scripts

    - name: Clone backup Script for MySQL
      shell: cd scripts && wget https://raw.githubusercontent.com/jpilsoftware-uy/sistemas-operativos/main/Scripts/backup_sql.sh

    - name: Clone logs backup for Logs
      shell: cd scripts && wget https://raw.githubusercontent.com/jpilsoftware-uy/sistemas-operativos/main/Scripts/backup_logs.sh

      